# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release #3.3.0
  #- oldrel #3.2.5
  #- devel

cache: packages

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
