# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: required
cache: packages
warnings_are_errors: true
r:
  - release #3.3.0
  #- oldrel #3.2.5
  #- devel

r_binary_packages:
 - ggplot2
 - inline
 - lda
 - lme4
 - Matrix
 - RcppArmadillo
 - Rcpp
 - scales
 - shiny
 - testthat

r_packages:
 - rstan
 - stm

r_github_packages:
  - jimhester/covr
  - kbenoit/quanteda

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install_version("slam",version="0.1-37",repos="http://cran.us.r-project.org")'
  - Rscript -e 'devtools::install_version("proxy",version="0.4-16",repos="http://cran.us.r-project.org")'

after_success:
  - Rscript -e 'covr::codecov(token="586cf964-23a1-4090-a503-3f9318e8f056",line_exclusions=list("R/vis.R","R/vis_covariates_binary.R","R/vis_covariates_continuous.R","R/vis_taxa.R","R/vis_topics.R","R/vis_functions.R","download_ref"))'

after_failure:
  - find *Rcheck -name '*.fail' -print -exec cat '{}' \;

notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    rooms:
      secure: "blIfobo0Df34Mpu3mqEskoRHVqkmHZOpqd7ORladqcWRvjoBYOwCgFZUF4ohXSVCuCYc9sSBkyiFRkV1VlgfAc9jTzK5/3qeyTCuNg4bEkeOp1Apbza26ul4qa5Iyaj1E23jWECnAUahrDq4P//8GwYTnvb987z2hZ/Do3vtA/N0a/VRbM60gAIrgn2Lbs6Y0MDQ/s6t870auVuk9ROZ99Hn1+UKPpaAv3YaZRJvWep6D8FTg9sIHt4UjIxK+HA/3yDXrg62//riiWbuO4A02ezsODWLk4+fOieQV4CcOK4kSjYb41WlynjaxJ4afg/71ksaFD2F1w25OxZgYb+bdBIIDGdsVmzunQ2WQWnl+NmEOz/SfvhvYXz2Ut3Xhq9DWXHGYpeIuH3/jj4cUWmKEHQ8921ZdiJYyNTLFF6OUOYzIuvx9C1Is8Q/H5p1VCf1t6McPV+pIiGwQJ3QtXBuEMs0JruBWmJiogNUbj+gEIRrH51lx6ANR8pCTc+wg3ZgJFcfskJ6Qj8rjPSl4Z8VAL3dvaqJjMwmKzhQuaFrhST4BVIzgltohQo3CdInVGQJb1/gA6bZfX7yKJMBegmkCpfcEOAfeJuw8/lv1SoPfV0t6fD0fmOZrgrtl1tebVpqVtJpxhmP0NPQYze8jyx3pwCCFA2ZwX+dTK0G+uBxWb4="
    on_success: change
    on_failure: always
    on_pull_requests: true
