# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required #false
cache: packages
warnings_are_errors: true
r:
  - release #3.3.0
  #- oldrel #3.2.5
  #- devel

r_binary_packages:
 - testthat
 - Rcpp
 - Matrix

r_packages:
 - rstan
 - lda
 - stm
 - lme4

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(token="586cf964-23a1-4090-a503-3f9318e8f056",line_exclusions=list("R/vis.R","R/vis_covariates_binary.R","R/vis_continuous_binary.R","R/vis_taxa.R","R/vis_topics.R","R/vis_taxa.R"))'

notifications:
  email:
    on_success: change
    on_failure: always
