# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required #false
cache: packages
warnings_are_errors: true
r:
  #- release #3.3.0
  - oldrel #3.2.5
  #- devel

r_binary_packages:
 - ggplot2
 - lda
 - lme4
 - Matrix
 - scales
 - shiny
 - testthat

r_packages:
 - Rcpp
 - rstan
 - stm

r_github_packages:
  - jimhester/covr
  - kbenoit/quanteda

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install_version("slam",version="0.1-37",repos="http://cran.us.r-project.org")'

after_success:
  - Rscript -e 'covr::codecov(token="586cf964-23a1-4090-a503-3f9318e8f056",line_exclusions=list("R/vis.R","R/vis_covariates_binary.R","R/vis_covariates_continuous.R","R/vis_taxa.R","R/vis_topics.R","R/vis_functions.R","download_ref"))'

after_failure:
  - find *Rcheck -name '*.fail' -print -exec cat '{}' \;

notifications:
  email:
    on_success: change
    on_failure: always
