# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required #false
cache: packages
warnings_are_errors: true
r:
  - release #3.3.0
  #- oldrel #3.2.5
  #- devel

r_packages:
  - covr
  - rstan

env:
  global:
    - NOT_CRAN=true CXXFLAGS=-O2 CXX_OLEVEL=2 RCPP_VER=cran CXX=clang++ CPP=clang CC=clang
  matrix:
    - CXX_OLEVEL=2 CXX=clang++

before_install:
 - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
 - mkdir -p ~/.R
 - echo 'CXXFLAGS=-O2' > ~/.R/Makevars
 - echo 'CC=clang' >> ~/.R/Makevars
 - echo 'CPP=clang' >> ~/.R/Makevars
 - echo 'CXX=clang++' >> ~/.R/Makevars
 - echo "CXX = `R CMD config CXX`" >> ~/.R/Makevars
 - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ~/.R/Makevars
 - export CLANG_EXTRA_ARG=""
 - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
 - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
 - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars

script:
  - |
    travis_wait R CMD build .

after_script:
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - Rscript -e "library(covr); codecov(token='586cf964-23a1-4090-a503-3f9318e8f056')"

notifications:
  email:
    on_success: change
    on_failure: always
