# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required #false
cache: packages
warnings_are_errors: true
r:
  - release #3.3.0
  #- oldrel #3.2.5
  #- devel

r_packages:
  - covr
  - rstan

r_github_packages:
  - rstanarm

env:
  matrix:
    include:
        - os: linux
          compiler: gcc
          addons:
            apt:
              sources: ['ubuntu-toolchain-r-test']
              packages: ['g++-4.9', 'valgrind']
          env: COMPILER=g++-4.9

before_install:
 - mkdir -p ~/.R
 - echo 'CXXFLAGS=-O3' > ~/.R/Makevars
 - echo 'mtune=native' > ~/.R/Makevars
 - echo 'Wno-unused-variable' > ~/.R/Makevars
 - echo 'Wno-unused-function' > ~/.R/Makevars
 - echo 'CXXFLAGS+=-flto' > ~/.R/Makevars
 - echo 'ffat-lto-objects' > ~/.R/Makevars
 - echo 'Wno-unused-local-typedef' > ~/.R/Makevars

script:
  - |
    travis_wait R CMD build .

before_install:
 - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
 - mkdir -p ~/.R
 - echo 'CXXFLAGS=-O2' > ~/.R/Makevars
 - echo 'CC=clang' >> ~/.R/Makevars
 - echo 'CPP=clang' >> ~/.R/Makevars
 - echo 'CXX=clang++' >> ~/.R/Makevars

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - Rscript -e "library(covr); codecov(token='586cf964-23a1-4090-a503-3f9318e8f056')"

notifications:
  email:
    on_success: change
    on_failure: always
