# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required #false
cache: packages
warnings_are_errors: true
r:
  - release #3.3.0
  #- oldrel #3.2.5
  #- devel

r_packages:
  - covr

after_success:
  - Rscript -e "library(covr); codecov(function_exclusions=c('^vis','^predict','^download','^fit_','^estimate_topic'),token='586cf964-23a1-4090-a503-3f9318e8f056')"

notifications:
  email:
    on_success: change
    on_failure: always
